select sequence_name from all_sequences;
select SEQ_GEN_IDENTITY.nextval from dual;

create table Users(
userid number generated by default on null as identity primary key,
username varchar(100),
userpassword varchar(100),
userrole varchar(100),
useremail varchar(100)
);