select sequence_name from all_sequences;
select SEQ_GEN_IDENTITY.nextval from dual;

create table Users(
userid number generated by default on null as identity primary key,
username varchar(100),
userpassword varchar(100),
userrole varchar(100),
useremail varchar(100)
);

select * from users;

create table products(
productid number generated by default on null as identity primary key,
productname varchar2(100),
productdescription varchar2(300),
price number,
instock number
);

select * from products;

desc products;

create table samazonusers(
userid number generated by default on null as identity primary key,
username varchar2(100),
userpassword varchar2(100),
userrole varchar(100),
useremail varchar2(100)
);

select * from samazonusers;

create table invoice(
invoiceid number generated by default on null as identity primary key,
userid number,
invoicedate varchar2(100),
foreign key (userid) references samazonusers(userid)
);

create table orders(
orderid number generated by default on null as identity primary key,
invoiceid number,
productid number,
sellingprice number,
tax number,
shippingcost number,
foreign key (productid) references products(productid),
foreign key (invoiceid) references invoice(invoiceid)
);

select * from invoice;
select * from orders;
select * from samazonusers;
select * from products;